# Generated by Django 5.2.11 on 2026-02-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('sobrenome', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField()),
                ('dataFalecimento', models.DateField()),
                ('mensagem', models.TextField(max_length=60)),
            ],
        ),
    ]
